Exercise 8
rajeshdewan/-DevOps-Course-Starter pull request #8
Opened 2021-12-09 17:17 UTC by rajeshdewan

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2021-12-15 12:33 UTC, hugh-emerson requested changes
This is in the right direction but so far you've only automated the release to Docker Hub, not to Heroku.

Also, we only want to run the deployment job for pushes to the main/master branch.

2021-12-15 12:33 UTC, hugh-emerson commented on .github/workflows/myci.yml
> +    - run: docker push rajeshdewan/todoapp:production
This is not CD until you deploy somewhere. We don't want people manually releasing to Heroku.

Add the commands here (except instead of `heroku login` you just need a HEROKU_API_KEY environment variable.

2021-12-15 12:33 UTC, hugh-emerson commented on .github/workflows/myci.yml
> +    needs:  build
You currently have this job running on all branches as long as the tests pass. But that means the `rajeshdewan/todoapp:production` image is unpredictable. It will be built from whichever branch was pushed most recently.

And once you add in deployment to Heroku, the Heroku website would be unstable.

You should add in an `if` so that you only build this for pushes to the main branch.

2021-12-16 17:12 UTC, rajeshdewan commented on .github/workflows/myci.yml
> +    - run: docker push rajeshdewan/todoapp:production
Change incorporated

2021-12-16 17:13 UTC, rajeshdewan commented on .github/workflows/myci.yml
> +    needs:  build
Change incorporated

2021-12-16 17:13 UTC, rajeshdewan commented
Requested changes included.

2021-12-20 10:14 UTC, BenRamchandani approved these changes
Looks good, thanks for making those changes. Go ahead and merge when you're ready.

2021-12-20 18:58 UTC, merged